-- Part 1, step 2: create the patient table.
-- Run in pgAdmin: right-click the sundhedsapp database -> Query Tool -> paste -> F5.
--
-- Use your ER diagram from step 1. Look at patient.yml from lecture 4:
--   id, first_name, last_name, age, blood_type, allergies
--
-- Rules the table must enforce:
--   * patient_id is the primary key and is generated by the database
--   * names, age and blood type are required (NOT NULL)
--   * age must be between 0 and 150                        (CHECK)
--   * blood_type must be one of A+ A- B+ B- AB+ AB- O+ O-  (CHECK ... IN (...))
--   * allergies is optional: NULL means "no known allergies"

DROP TABLE IF EXISTS patient;

CREATE TABLE patient (
    patient_id  INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    -- TODO: add first_name, last_name, age, blood_type and allergies
);
